development:
  adapter: postgresql
#  adapter: em_postgresql
#  adapter: empostgresql
  encoding: unicode
  database: fmgr
  username: jacek
  password:
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: fmgr_test
  username: jacek
  password:
  pool: 5
  timeout: 5000

# for local testing
production:
  adapter: postgresql
  encoding: unicode
  database: fmgr_test
  username: jacek
  password:
  pool: 5
  timeout: 5000

# heroku db has to be configured from the command line and is being picked up
# by means of env variables - no need for configuration here
#production:
#  adapter: postgresql
#  adapter: em_postgresql
#  adapter: empostgresql
#  encoding: unicode
#  database: fmgr
#  pool: 5
#  timeout: 5000